ALTER TYPE "DocumentEntityType" ADD VALUE IF NOT EXISTS 'PAYMENT_SUBMISSION';

CREATE TYPE "PaymentProvider" AS ENUM ('MANUAL', 'STRIPE');

CREATE TYPE "PaymentSubmissionStatus" AS ENUM ('AWAITING_PROOF', 'PENDING', 'CONFIRMED', 'REJECTED');
